from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()

doc.add_heading('Sample Document', level=0)

doc.add_heading('Introduction', level=1)
doc.add_paragraph(
    'This is a sample document generated by the docx-builder agent. '
    'It demonstrates headings, paragraphs, a table, and a bullet list.'
)

doc.add_heading('Data Table', level=1)
table = doc.add_table(rows=3, cols=3, style='Light Grid Accent 1')
table.cell(0, 0).text = 'Item'
table.cell(0, 1).text = 'Quantity'
table.cell(0, 2).text = 'Price'
table.cell(1, 0).text = 'Widget A'
table.cell(1, 1).text = '10'
table.cell(1, 2).text = '$5.00'
table.cell(2, 0).text = 'Widget B'
table.cell(2, 1).text = '5'
table.cell(2, 2).text = '$12.50'

doc.add_heading('Features', level=1)
doc.add_paragraph('Easy to use', style='List Bullet')
doc.add_paragraph('Programmatic generation', style='List Bullet')
doc.add_paragraph('Supports tables and images', style='List Bullet')

doc.add_heading('Conclusion', level=1)
p = doc.add_paragraph()
run = p.add_run('This document was generated successfully.')
run.bold = True

output_path = 'C:\\Users\\DTC USER\\Desktop\\Fabillo\\document-skill\\fabillo\\sample_output.docx'
doc.save(output_path)
print(f'Document saved to {output_path}')
